# Change these first
owner: aisa-status # Your GitHub organization or username, where this repository lives
repo: status-upptime # The name of this repository

sites:
  - name: Alternativas Inteligentes Site
    url: alternativasinteligentes.com
  - name: Chatroom
    url: https://chatroom.alternativasinteligentes.com/
  - name: Arturnito
    url: https://reservas.alternativasinteligentes.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.alternativasinteligentes.com
  # baseUrl: /your-repo-name
  logoUrl: https://alternativasinteligentes.com/wp-content/uploads/2019/03/logo-aisa.png
  name: AISA Status
  introTitle: "**AISA STATUS**"
  introMessage: Esta es la página de estado de nuestros servicios y aplicaciones en vivo, las incidencias actuales y pasadas. 
  navbar:
    - title: Status
      href: /
    - title: Site
      href: https://alternativasinteligentes.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration