# Change these first
owner: aisa-status # Your GitHub organization or username, where this repository lives
repo: status-upptime # The name of this repository

sites:
  - name: Panel Chatroom
    url: https://chatroom-dev.alternativasinteligentes.com/
    
  - name: Socket Chatroom
    url: https://chatroom-socket-dev.alternativasinteligentes.com/
    expectedStatusCodes:
      - 200
      - 201
      - 404

  - name: BCR Bot
    url: https://bcr.alternativasinteligentes.com/BCRApi/web/chatbot
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '$BCRBOT_BODY'
    maxResponseTime: 800

  - name: Turnos 24x7
    url: https://reservas-dev.alternativasinteligentes.com/
    icon: https://i.ibb.co/QpSf3c1/aisa-turnos24x7-isotipo.jpg
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '$TURNOS24X7_BODY'
    maxResponseTime: 800

  - name: Auth User Service
    url: https://auth-dev.alternativasinteligentes.com/web/
    expectedStatusCodes:
      - 200
      - 201
      - 404

  - name: Sender Service
    url: https://sender.alternativasinteligentes.com/web/
    expectedStatusCodes:
      - 200
      - 201
      - 404

  - name: Templates Sender Service
    url: https://templates-sender-service.alternativasinteligentes.com/web/
    expectedStatusCodes:
      - 200
      - 201
      - 404

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status-dev.alternativasinteligentes.com
  # baseUrl: /your-repo-name
  theme: light
  logoUrl: https://alternativasinteligentes.com/wp-content/uploads/2019/03/logo-aisa.png
  name: Status Dev Services and Apps
  introTitle: "*ESTADOS DE NUESTRAS APLICACIONES Y SERVICIOS de Desarrollo**"
  # introMessage: En esta puedes observar el estado de nuestras apps y servicios en produccion. 
  navbar:
    - title: Status
      href: /
    - title: Site
      href: https://alternativasinteligentes.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
